import './bootstrap.min.css';
import './globals.css';
import Navbar from '@/components/Navbar';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <Navbar />
        <main role="main" className='container'>
          {children}
        </main></body>
    </html>
  )
}
