import Me from '@/components/Home/Me'
import Posts from '@/components/Post/Posts'
import { getHome, getMe, getFollowers } from '@/libs/api.js'
import Followers from '@/components/User/Followers'

export const metadata = {
  title: 'Accueil - Instawish',
  description: 'Generated by create next app',
}

export default async function Home() {
  try {
    // const allPosts = await getHome();
    const me = await getMe();
    const followers = await getFollowers();
    return <>
      <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }} className="my-4">
        <div>
          <Me me={me} />
        </div>
        <div style={{ overflowX: 'auto' }}>
          <Followers followers={followers} />
        </div>
      </div>

      <Posts me={me} />
    </>
  } catch (error) {
    console.error("Erreur lors de la récupération des posts:", error);
    return <div>Erreur lors du chargement des posts</div>;
  }
}


